version: '2'
services:
    autoprices-app:
        image: autoprices
        external_links:
            - autoprices-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/autoprices
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    autoprices-postgresql:
        extends:
            file: postgresql.yml
            service: autoprices-postgresql
